package mcpserver

import (
	"bytes"
	"image/color"
	"image/png"
	"strings"
	"testing"

	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// byObjectGCode is a plate printed by object: object A's two layers, then object
// B's two, so the heights repeat (0.2, 0.4, 0.2, 0.4).
const byObjectGCode = `; HEADER_BLOCK_START
; generated by Creality_Print V7.2.2.5483 on 2026-09-29 at 07:03:52
; total layer number: 4
; max_z_height: 0.40
; HEADER_BLOCK_END

; MINX = 10.00
; MINY = 10.00
; MINZ = 0.00
; MAXX = 90.00
; MAXY = 30.00
; MAXZ = 0.40

; multicolor_method = 0
; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=a_id_0_copy_0 CENTER=20,20 POLYGON=[[10,10],[30,10],[30,30],[10,30],[10,10]]
EXCLUDE_OBJECT_DEFINE NAME=b_id_1_copy_0 CENTER=80,20 POLYGON=[[70,10],[90,10],[90,30],[70,30],[70,10]]
T0
;LAYER_CHANGE
;:0.2
;HEIGHT:0.2
;TYPE:Outer wall
G1 X10 Y10 F3000
G1 X30 Y10 E1
G1 X30 Y30 E1
;LAYER_CHANGE
;:0.4
;HEIGHT:0.2
;TYPE:Outer wall
G1 X10 Y10 F3000
G1 X30 Y10 E1
;LAYER_CHANGE
;:0.2
;HEIGHT:0.2
;TYPE:Sparse infill
G1 X70 Y10 F3000
G1 X90 Y10 E1
G1 X90 Y30 E1
;LAYER_CHANGE
;:0.4
;HEIGHT:0.2
;TYPE:Sparse infill
G1 X70 Y10 F3000
G1 X90 Y10 E1
; EXECUTABLE_BLOCK_END

; filament used [mm] = 100.00
; filament used [g] = 1.50
; total layers count = 4
; estimated printing time (normal mode) = 1m 5s

; CONFIG_BLOCK_START
; wall_loops = 3
; print_sequence = by object
; CONFIG_BLOCK_END
`

func sizeOf(t *testing.T, img *mcp.ImageContent) (int, int) {
	t.Helper()
	cfg, err := png.DecodeConfig(bytes.NewReader(img.Data))
	if err != nil {
		t.Fatal(err)
	}
	return cfg.Width, cfg.Height
}

// The layer report of a plate printed by object shows every object at the
// chosen height and says why.
func TestLayerReportOfAByObjectPlatePicksTheHeightAcrossObjects(t *testing.T) {
	pf := newProjFixture(t)
	pf.exec.gcode = byObjectGCode
	id := pf.withModel(t, "cube")
	pf.ok(t, "slice_project", map[string]any{"project": id, "wait": 30})

	layers := pf.ok(t, "get_slice_report", map[string]any{"project": id, "section": "layers"})
	contains(t, "layers", bodyOf(layers), "printed by object", "counted across all objects")

	// Layer 3 is the first layer of the second object: at z 0.2 both objects are drawn.
	res := call(t, pf.cs, "get_slice_report", map[string]any{"project": id, "section": "layer", "layer": 3})
	if res.IsError {
		t.Fatalf("layer 3:\n%s", text(t, res))
	}
	body := bodyOf(text(t, res))
	contains(t, "layer 3", body, "printed by object", "all 2 layer(s) at z 0.2", "Outer wall", "Sparse infill")
	if len(images(res)) != 1 {
		t.Errorf("%d image(s)", len(images(res)))
	}
	// By height: z 0.4 is the same set of two layers.
	byZ := pf.ok(t, "get_slice_report", map[string]any{"project": id, "section": "layer", "z": 0.4, "preview": "none"})
	contains(t, "z 0.4", bodyOf(byZ), "all 2 layer(s) at z 0.4")
}

// The slice preview is the sliced toolpaths in isometric plus the first layer
// of all objects.
func TestSlicePreviewShowsToolpathsAndTheFirstLayerOfAllObjects(t *testing.T) {
	pf := newProjFixture(t)
	pf.exec.gcode = byObjectGCode
	id := pf.withModel(t, "cube")
	for preview, want := range map[string][3]int{"small": {512, 384, 384}, "large": {1024, 768, 1024}} {
		res := call(t, pf.cs, "slice_project", map[string]any{"project": id, "preview": preview, "wait": 30})
		imgs := images(res)
		if res.IsError || len(imgs) != 2 {
			t.Fatalf("%s: error %v, %d image(s):\n%s", preview, res.IsError, len(imgs), text(t, res))
		}
		if w, h := sizeOf(t, imgs[0]); w != want[0] || h != want[1] {
			t.Errorf("%s toolpaths %dx%d, want %dx%d", preview, w, h, want[0], want[1])
		}
		if w, h := sizeOf(t, imgs[1]); w != want[2] || h != want[2] {
			t.Errorf("%s first layer %dx%d, want %dx%d", preview, w, h, want[2], want[2])
		}
	}
	// Without preview no picture at all.
	res := call(t, pf.cs, "slice_project", map[string]any{"project": id, "wait": 30})
	if len(images(res)) != 0 {
		t.Error("an image without asking")
	}
}

// The screenshot of a change is the whole plate in a 4:3 frame with the changed
// object outlined.
func TestChangeScreenshotShowsTheWholePlateWithTheChangedObjectOutlined(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.create(t, "Shots")
	pf.ok(t, "add_model", map[string]any{"project": id, "path": pf.stl, "name": "far", "position": []float64{200, 200}, "include_screenshot": false})
	res := call(t, pf.cs, "add_model", map[string]any{"project": id, "path": pf.stl, "name": "near", "position": []float64{40, 40}})
	imgs := images(res)
	if len(imgs) != 1 {
		t.Fatalf("%d image(s)", len(imgs))
	}
	if w, h := sizeOf(t, imgs[0]); w != 512 || h != 384 {
		t.Errorf("screenshot %dx%d, want 512x384", w, h)
	}
	shot := pngOf(t, res)
	pink := func(c color.NRGBA) bool { return c.R > 230 && c.G < 100 && c.B > 90 && c.B < 200 }
	// Both cubes are in it (the far one is not cut off by a tight frame) and only
	// the new one is outlined.
	if count(shot, pink) < 60 {
		t.Errorf("only %d highlight pixels", count(shot, pink))
	}
	upd := call(t, pf.cs, "update_object", map[string]any{"project": id, "object": "far", "position": []float64{150, 150}})
	if a, b := count(pngOf(t, upd), pink), count(shot, pink); a < 60 {
		t.Errorf("update_object highlight pixels: %d (%d for add_model)", a, b)
	}
	// A move changes the picture: the same object at another place.
	moved := call(t, pf.cs, "update_object", map[string]any{"project": id, "object": "far", "position": []float64{60, 200}})
	if bytes.Equal(pngOf(t, upd).Pix, pngOf(t, moved).Pix) {
		t.Error("a move gave the same picture")
	}
}

func TestGetViewListsSkippedLabelsAndRangeBands(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.create(t, "Crowd")
	for i := 0; i < 7; i++ {
		pf.ok(t, "add_model", map[string]any{"project": id, "path": pf.stl, "name": "part" + string(rune('a'+i)), "position": []float64{100, 30 + 30*float64(i)}, "include_screenshot": false})
	}
	out := pf.ok(t, "get_view", map[string]any{"project": id, "view_name": "Front"})
	contains(t, "crowd", bodyOf(out), "Labels left out so that none covers another")
	// Range bands are tied to their heights and values.
	pf.ok(t, "set_height_ranges", map[string]any{"project": id, "object": "parta", "ranges": []map[string]any{
		{"from_z": 2, "to_z": 6, "values": map[string]any{"wall_loops": 5}}, {"from_z": 8, "to_z": 12, "values": map[string]any{"wall_loops": 4}}}, "include_screenshot": false})
	rng := pf.ok(t, "get_view", map[string]any{"project": id, "view_name": "Front", "focus": []string{"parta"}, "show_ranges": true})
	body := bodyOf(rng)
	if !strings.Contains(body, "orange band: parta from z 2 to 6 mm (") || !strings.Contains(body, "wall_loops 5)") || !strings.Contains(body, "teal band: parta from z 8 to 12 mm (") || !strings.Contains(body, "wall_loops 4)") {
		t.Errorf("range legend:\n%s", body)
	}
	// A 4:3 frame by default.
	if w, h := sizeOf(t, images(call(t, pf.cs, "get_view", map[string]any{"project": id}))[0]); w != 1024 || h != 768 {
		t.Errorf("default get_view %dx%d", w, h)
	}
}

// A change to a part is framed on its object, so the modifier is not a dot; the
// outline of the object is still drawn. Other changes keep the whole plate.
func TestPartScreenshotsAreFramedOnTheObject(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.withModel(t, "Framed")
	pink := func(c color.NRGBA) bool { return c.R > 230 && c.G < 100 && c.B > 90 && c.B < 200 }
	yellow := func(c color.NRGBA) bool { return c.R > 165 && c.G > 130 && c.B < 110 && int(c.R) > int(c.B)+90 }
	light := func(c color.NRGBA) bool { return c.R > 190 && c.G > 190 && c.B > 190 }

	whole := pngOf(t, call(t, pf.cs, "manage_plates", map[string]any{"project": id, "action": "set", "plate": 1, "values": map[string]any{"print_sequence": "by layer"}}))
	mod := call(t, pf.cs, "add_modifier", map[string]any{"project": id, "object": "cube", "kind": "modifier", "shape": "box", "size": []float64{8, 8, 8},
		"values": map[string]any{"wall_loops": 6}})
	shot := pngOf(t, mod)
	if a, b := count(shot, light), count(whole, light); a < b*3 {
		t.Errorf("the object fills %d light pixels framed against %d on the whole plate", a, b)
	}
	if count(shot, yellow) < 150 || count(shot, pink) < 60 {
		t.Errorf("modifier %d yellow pixels, %d highlight pixels", count(shot, yellow), count(shot, pink))
	}
	if w, h := sizeOf(t, images(mod)[0]); w != 512 || h != 384 {
		t.Errorf("size %dx%d", w, h)
	}
	// remove_part is framed the same way.
	info, err := pf.store.GetProject(id)
	if err != nil {
		t.Fatal(err)
	}
	part := ""
	for _, o := range info.Objects {
		for _, p := range o.Parts {
			if p.Subtype == "modifier_part" {
				part = p.Name
			}
		}
	}
	rm := pngOf(t, call(t, pf.cs, "remove_part", map[string]any{"project": id, "object": "cube", "part": part}))
	if count(rm, light) < count(whole, light)*3 {
		t.Error("remove_part screenshot is not framed on the object")
	}
}

// update_object and set_height_ranges frame the object with context (at least
// 80 mm around a small one); add_model, remove_object and manage_plates keep the
// whole plate; the height range screenshot shows the bands.
func TestScreenshotFramingByTool(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.withModel(t, "Frames")
	light := func(c color.NRGBA) bool { return c.R > 190 && c.G > 190 && c.B > 190 }
	orange := func(c color.NRGBA) bool { return c.R > 200 && c.G > 90 && c.G < 170 && c.B < 90 }
	whole := count(pngOf(t, call(t, pf.cs, "manage_plates", map[string]any{"project": id, "action": "set", "plate": 1, "values": map[string]any{"print_sequence": "by layer"}})), light)
	moved := count(pngOf(t, call(t, pf.cs, "update_object", map[string]any{"project": id, "object": "cube", "position": []float64{130, 130}})), light)
	if moved < whole*3 {
		t.Errorf("update_object: %d light pixels, %d on the whole plate: not framed on the object", moved, whole)
	}
	// Context: the 20 mm cube does not fill the frame.
	if total := 512 * 384; moved > total*30/100 {
		t.Errorf("the cube fills %d of %d pixels: no context around it", moved, total)
	}
	ranges := pngOf(t, call(t, pf.cs, "set_height_ranges", map[string]any{"project": id, "object": "cube", "ranges": []map[string]any{
		{"from_z": 4, "to_z": 12, "values": map[string]any{"wall_loops": 5}}}}))
	if count(ranges, orange) < 200 {
		t.Errorf("the height range band is not in the screenshot: %d orange pixels", count(ranges, orange))
	}
	// Whole plate: add_model and remove_object.
	added := call(t, pf.cs, "add_model", map[string]any{"project": id, "path": pf.stl, "name": "second", "position": []float64{40, 40}})
	if a := count(pngOf(t, added), light); a > whole*2 {
		t.Errorf("add_model: %d light pixels against %d on the whole plate", a, whole)
	}
	removed := call(t, pf.cs, "remove_object", map[string]any{"project": id, "object": "second"})
	if a := count(pngOf(t, removed), light); a > whole*2 {
		t.Errorf("remove_object: %d light pixels against %d on the whole plate", a, whole)
	}
}
