package mcpserver

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/sairaph/creality-slicer-mcp/internal/catalog"
	"github.com/sairaph/creality-slicer-mcp/internal/mesh"
	"github.com/sairaph/creality-slicer-mcp/internal/profiles"
	"github.com/sairaph/creality-slicer-mcp/internal/projects"
	"github.com/sairaph/creality-slicer-mcp/internal/slicer"
)

const (
	tpPrinter = "Creality K2 0.4 nozzle"
	tpProcess = "0.20mm Standard @Creality K2 0.4 nozzle"
	tpPLA     = "TP-PLA @Creality K2 0.4 nozzle"
	tpPETG    = "TP-PETG @Creality K2 0.4 nozzle"
)

// projectBundle writes a small synthetic Creality profile bundle with what a
// project needs (a printer with a bed, a process, two filaments).
func projectBundle(t *testing.T) string {
	t.Helper()
	root := filepath.Join(t.TempDir(), "profiles")
	type entry struct{ name, sub string }
	lists := map[string][]entry{}
	add := func(kind, name, body string) {
		file := name + ".json"
		if err := os.MkdirAll(filepath.Join(root, "Creality", kind), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(root, "Creality", kind, file), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		lists[kind] = append(lists[kind], entry{name, kind + "/" + file})
	}
	add("machine", tpPrinter, fmt.Sprintf(`{"type":"machine","name":%q,"from":"system","instantiation":"true","setting_id":"90.4",
"printer_model":"Creality K2","printer_variant":"0.4","nozzle_diameter":["0.4"],
"printable_area":"0x0,260x0,260x260,0x260","printable_height":"250","nozzle_volume":"183",
"default_print_profile":%q,"default_filament_profile":[%q],"thumbnails":"96x96/PNG, 300x300/PNG"}`, tpPrinter, tpProcess, tpPLA))
	add("process", tpProcess, fmt.Sprintf(`{"type":"process","name":%q,"from":"system","instantiation":"true","setting_id":"GP1",
"layer_height":"0.2","initial_layer_print_height":"0.2","wall_loops":"3","compatible_printers":[%q]}`, tpProcess, tpPrinter))
	fil := func(name, id, typ, colour string) string {
		return fmt.Sprintf(`{"type":"filament","name":%q,"from":"system","instantiation":"true","filament_id":%q,
"filament_type":[%q],"default_filament_colour":[%q],"nozzle_temperature":["215"],"compatible_printers":[%q]}`, name, id, typ, colour, tpPrinter)
	}
	add("filament", tpPLA, fil(tpPLA, "P001", "PLA", "#FFFFFF"))
	add("filament", tpPETG, fil(tpPETG, "P002", "PETG", "#000000"))
	add("filament", "Generic PLA @Creality K2 0.4 nozzle", fil("Generic PLA @Creality K2 0.4 nozzle", "GFL99", "PLA", "#FFFFFF"))
	var idx strings.Builder
	idx.WriteString(`{"name":"Creality","version":"9.0.0.1","description":"synthetic"`)
	for _, kind := range []string{"machine", "process", "filament"} {
		idx.WriteString(fmt.Sprintf(`,%q:[`, kind+"_list"))
		for i, e := range lists[kind] {
			if i > 0 {
				idx.WriteString(",")
			}
			idx.WriteString(fmt.Sprintf(`{"name":%q,"sub_path":%q}`, e.name, e.sub))
		}
		idx.WriteString("]")
	}
	idx.WriteString("}")
	if err := os.WriteFile(filepath.Join(root, "Creality.json"), []byte(idx.String()), 0o644); err != nil {
		t.Fatal(err)
	}
	return root
}

// sliceGCode is a two layer, two tool G-code with one object.
const sliceGCode = `; HEADER_BLOCK_START
; generated by Creality_Print V7.2.2.5483 on 2026-09-29 at 07:03:52
; total layer number: 2
; max_z_height: 0.40
; HEADER_BLOCK_END

; MINX = 10.00
; MINY = 10.00
; MINZ = 0.00
; MAXX = 30.00
; MAXY = 30.00
; MAXZ = 0.40

; multicolor_method = 0
; EXECUTABLE_BLOCK_START
EXCLUDE_OBJECT_DEFINE NAME=cube_id_0_copy_0 CENTER=20,20 POLYGON=[[10,10],[30,10],[30,30],[10,30],[10,10]]
T0
;LAYER_CHANGE
;:0.2
;HEIGHT:0.2
;TYPE:Outer wall
G1 X10 Y10 F3000
G1 X30 Y10 E1
G1 X30 Y30 E1
;TYPE:Sparse infill
G1 X10 Y30 E1
T1
;LAYER_CHANGE
;:0.4
;HEIGHT:0.2
;TYPE:Outer wall
G1 X10 Y10 F3000
G1 X30 Y10 E1
; EXECUTABLE_BLOCK_END

; filament used [mm] = 100.00, 50.00
; filament used [g] = 1.50, 0.50
; total filament cost = 0.10
; total layers count = 2
; estimated printing time (normal mode) = 1m 5s

; CONFIG_BLOCK_START
; wall_loops = 4
; layer_height = 0.2
; thumbnails = 96x96/PNG, 300x300/PNG
; CONFIG_BLOCK_END
`

// fakeSlicer stands in for the slicer process: it writes a G-code for the
// plate it is asked to slice. No real slicer runs in tests.
type fakeSlicer struct {
	mu      sync.Mutex
	calls   int
	block   chan struct{} // waited on before the run ends, when set
	killed  chan struct{} // closed when a blocked run is cancelled
	started chan struct{} // closed when the first run has begun
	once    sync.Once
	gcode   string // the G-code to write instead of sliceGCode, when set
}

func (f *fakeSlicer) Run(ctx context.Context, spec slicer.ExecSpec) (slicer.ExecResult, error) {
	f.mu.Lock()
	f.calls++
	f.mu.Unlock()
	if f.started != nil {
		f.once.Do(func() { close(f.started) })
	}
	if f.block != nil {
		select {
		case <-f.block:
		case <-ctx.Done():
			if f.killed != nil {
				close(f.killed)
			}
			return slicer.ExecResult{Killed: true}, nil
		}
	}
	plate, out := 1, ""
	for i, a := range spec.Args {
		switch a {
		case "--slice":
			if n, _ := strconv.Atoi(spec.Args[i+1]); n > 0 {
				plate = n
			}
		case "--outputdir":
			out = spec.Args[i+1]
		}
	}
	text := sliceGCode
	if f.gcode != "" {
		text = f.gcode
	}
	err := os.WriteFile(filepath.Join(out, fmt.Sprintf("plate_%d.gcode", plate)), []byte(text), 0o644)
	return slicer.ExecResult{}, err
}

// projFixture is a server over a real projects.Store in a temporary folder
// with a fake slicer process.
type projFixture struct {
	*fixture
	srv   *Server
	exec  *fakeSlicer
	stl   string
	store *projects.Store
	// builds counts the projects backends the server built.
	builds int
	// launcher stands in for the application launcher.
	launcher *fakeLauncher
	// wrap, set before the first call, wraps the store the server gets.
	wrap func(ProjectStore) ProjectStore
}

func newProjFixture(t *testing.T, opts ...func(*Config)) *projFixture {
	t.Helper()
	pf := &projFixture{exec: &fakeSlicer{}, launcher: &fakeLauncher{}}
	root := projectBundle(t)
	dir := t.TempDir()
	in := slicer.Install{
		Found: true, Supported: true, Version: "7.2.2", Build: "5483", Dialect: "v72",
		Dir: dir, Exe: filepath.Join(dir, "CrealityPrint.exe"), DataDir: filepath.Join(dir, "data"),
		ProfileVersion: "9.0.0.1", ProfileRoot: root,
	}
	fi := &fakeInstall{install: in}
	deps := Deps{
		Install:  fi,
		Launcher: pf.launcher,
		Texts:    func(string) (catalog.TextSource, error) { return fakeTexts{}, nil },
		NewProjects: func(in slicer.Install, ps ProfileStore, cat *catalog.Catalog) (ProjectBackend, error) {
			real, ok := ps.(*profiles.Store)
			if !ok {
				return ProjectBackend{}, fmt.Errorf("no preset store")
			}
			d, err := slicer.NewDialect("v72", cat.CLIFlag)
			if err != nil {
				return ProjectBackend{}, err
			}
			runner := &slicer.Runner{Exe: in.Exe, Dialect: d, Exec: pf.exec, TempDir: func() string { return t.TempDir() }}
			jobs := slicer.NewJobs(runner, filepath.Join(dir, "jobs"))
			st, err := projects.New(projects.Config{
				Root: filepath.Join(dir, "projects"), Install: in, Runner: runner, Jobs: jobs, Profiles: real, Catalog: cat,
			})
			if err != nil {
				return ProjectBackend{}, err
			}
			pf.store = st
			pf.builds++
			var store ProjectStore = st
			if pf.wrap != nil {
				store = pf.wrap(st)
			}
			return ProjectBackend{Store: store, Jobs: jobs}, nil
		},
	}
	pf.fixture = &fixture{install: fi, cfg: Config{Version: "1.2.3", Deps: deps}}
	for _, o := range opts {
		o(&pf.cfg)
	}
	pf.cs = sessionConfig(t, pf.cfg, func(s *Server) { pf.srv = s })
	t.Cleanup(func() { pf.srv.env.stopJobs() })
	pf.stl = filepath.Join(t.TempDir(), "cube.stl")
	if err := os.WriteFile(pf.stl, mesh.WriteBinarySTL(mesh.Box(20, 20, 20)), 0o644); err != nil {
		t.Fatal(err)
	}
	return pf
}

// create makes a two filament project and returns its id.
func (pf *projFixture) create(t *testing.T, name string) string {
	t.Helper()
	out := pf.ok(t, "create_project", map[string]any{
		"name": name,
		"filaments": []map[string]any{
			{"preset": tpPLA, "colour": "#FFFFFF"},
			{"preset": tpPETG, "colour": "#000000"},
		},
	})
	return frontOf(t, out)["project"].(string)
}

func (pf *projFixture) withModel(t *testing.T, name string) string {
	t.Helper()
	id := pf.create(t, name)
	pf.ok(t, "add_model", map[string]any{"project": id, "path": pf.stl})
	return id
}

func TestProjectCreateOpenListGetDelete(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.create(t, "Bracket")
	out := pf.ok(t, "get_project", map[string]any{"project": id})
	front := frontOf(t, out)
	if front["printer"] != tpPrinter || front["process"] != tpProcess {
		t.Errorf("front = %v", front)
	}
	contains(t, "get_project", out, "Filaments", tpPETG, "No objects yet")

	if got := pf.ok(t, "list_projects", nil); !strings.Contains(got, id) || frontOf(t, got)["count"] != 1 {
		t.Errorf("list_projects = %s", got)
	}

	file := filepath.Join(t.TempDir(), "out", "bracket.3mf")
	pf.ok(t, "export_project", map[string]any{"project": id, "path": file})
	if _, err := os.Stat(file); err != nil {
		t.Fatalf("export wrote nothing: %v", err)
	}
	if e := pf.errText(t, "export_project", map[string]any{"project": id, "path": file}); !strings.Contains(e, "overwrite") {
		t.Errorf("second export: %s", e)
	}
	pf.ok(t, "export_project", map[string]any{"project": id, "path": file, "overwrite": true})

	opened := pf.ok(t, "open_project", map[string]any{"path": file, "name": "Reopened"})
	of := frontOf(t, opened)
	if of["name"] != "Reopened" || of["source_path"] != file {
		t.Errorf("open front = %v", of)
	}
	if _, err := os.Stat(file); err != nil {
		t.Errorf("the source file is gone: %v", err)
	}

	if e := pf.errText(t, "delete_project", map[string]any{"project": id, "confirm": "wrong"}); !strings.Contains(e, "confirm") {
		t.Errorf("delete without the id: %s", e)
	}
	pf.ok(t, "delete_project", map[string]any{"project": id, "confirm": id})
	if e := pf.errText(t, "get_project", map[string]any{"project": id}); !strings.Contains(e, "not_found") {
		t.Errorf("deleted project: %s", e)
	}
}

func TestCreateProjectErrors(t *testing.T) {
	pf := newProjFixture(t)
	e := pf.errText(t, "create_project", map[string]any{"name": "x", "filaments": []map[string]any{{"preset": "No such preset", "colour": "#FFFFFF"}}})
	contains(t, "unknown preset", e, "invalid_input")
	// The schema refuses an empty filament list before the handler runs.
	res := call(t, pf.cs, "create_project", map[string]any{"name": "x", "filaments": []map[string]any{}})
	if !res.IsError {
		t.Error("an empty filament list was accepted")
	}
}

func TestEditingTools(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.create(t, "Edits")

	added := pf.ok(t, "add_model", map[string]any{"project": id, "path": pf.stl, "name": "cube", "copies": 2, "scale": 1.5, "filament": 2})
	contains(t, "add_model", added, "cube")
	front := frontOf(t, added)
	if list, _ := front["added"].([]any); len(list) != 2 {
		t.Errorf("added = %v", front["added"])
	}
	if e := pf.errText(t, "add_model", map[string]any{"project": id, "path": filepath.Join(t.TempDir(), "missing.stl")}); !strings.Contains(e, "invalid_input") {
		t.Errorf("missing model: %s", e)
	}

	moved := pf.ok(t, "update_object", map[string]any{"project": id, "object": "cube_1", "position": []float64{100, 100}, "rotation": []float64{0, 0, 90}, "scale": []float64{1, 1, 2}})
	contains(t, "update_object", moved, "100")
	_ = moved

	changed := pf.ok(t, "update_settings", map[string]any{"project": id, "values": map[string]any{"wall_loops": 4}})
	contains(t, "update_settings", changed, "wall_loops")
	if e := pf.errText(t, "update_settings", map[string]any{"project": id, "values": map[string]any{"no_such_key": 1}}); !strings.Contains(e, "no_such_key") {
		t.Errorf("unknown key: %s", e)
	}
	// describe_setting with the project shows the value and where it comes from.
	d := pf.ok(t, "describe_setting", map[string]any{"key": "wall_loops", "project": id})
	df := frontOf(t, d)
	if df["current"] != "4" || !strings.Contains(fmt.Sprint(df["origin"]), "changed in this project") {
		t.Errorf("describe front = %v", df)
	}
	if e := pf.errText(t, "describe_setting", map[string]any{"key": "wall_loops", "project": "nope"}); !strings.Contains(e, "not_found") {
		t.Errorf("describe with an unknown project: %s", e)
	}

	presets := pf.ok(t, "set_presets", map[string]any{"project": id, "flush_multiplier": 0.8})
	contains(t, "set_presets", presets, "0.8")
	if e := pf.errText(t, "set_presets", map[string]any{"project": id}); !strings.Contains(e, "invalid_input") {
		t.Errorf("set_presets without anything: %s", e)
	}

	pf.ok(t, "add_modifier", map[string]any{"project": id, "object": "cube_1", "kind": "modifier", "shape": "box", "size": []float64{5, 5, 5},
		"values": map[string]any{"wall_loops": 6}})
	pf.ok(t, "set_height_ranges", map[string]any{"project": id, "object": "cube_1", "ranges": []map[string]any{
		{"from_z": 1, "to_z": 3, "values": map[string]any{"wall_loops": 5}}}})
	pf.ok(t, "set_layer_actions", map[string]any{"project": id, "actions": []map[string]any{{"z": 10, "type": "color_change", "filament": 2}}})
	pf.ok(t, "manage_plates", map[string]any{"project": id, "action": "add"})
	pf.ok(t, "manage_plates", map[string]any{"project": id, "action": "rename", "plate": 2, "name": "Second"})
	got := pf.ok(t, "get_project", map[string]any{"project": id})
	contains(t, "get_project", got, "Second", "cube_1")

	pf.ok(t, "remove_object", map[string]any{"project": id, "object": "cube_2"})
}

// get_project is text only: pictures come from get_view.
func TestGetProjectIsTextOnly(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.withModel(t, "Look")
	res := call(t, pf.cs, "get_project", map[string]any{"project": id})
	if res.IsError || len(images(res)) != 0 {
		t.Fatalf("error %v, %d image(s)", res.IsError, len(images(res)))
	}
	for _, args := range []map[string]any{{"preview": "small"}, {"view": "top"}, {"plate": 1}} {
		args["project"] = id
		if res := call(t, pf.cs, "get_project", args); !res.IsError {
			t.Errorf("get_project accepted %v", args)
		}
	}
	contains(t, "get_project", text(t, res), "Next: get_view")
}

func TestSliceProjectHandoffAndReport(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.withModel(t, "Cube")
	res := call(t, pf.cs, "slice_project", map[string]any{"project": id, "preview": "small", "background": false})
	out := text(t, res)
	if res.IsError {
		t.Fatalf("slice_project failed:\n%s", out)
	}
	front := frontOf(t, out)
	if front["state"] != "finished" {
		t.Errorf("front = %v", front)
	}
	contains(t, "slice_project", out, "gcode_path", "upload_name", "creality-k2-mcp", "get_filaments", "upload_gcode_file",
		"start_print", "slot_map", "exclude_object", "1 | T0 | 0 | ", "1 | T1 | 1 | ", "Exclusion labels", "cube_id_0_copy_0", "Cube_plate1.gcode")
	if n := len(images(res)); n != 2 {
		t.Errorf("preview result attached %d image(s), want the plate and the first layer", n)
	}
	handoff, _ := front["handoff"].([]any)
	if len(handoff) != 1 {
		t.Fatalf("handoff = %v", front["handoff"])
	}
	h := handoff[0].(map[string]any)
	if path, _ := h["gcode_path"].(string); path == "" || !strings.HasSuffix(path, ".gcode") {
		t.Errorf("handoff = %v", h)
	}
	if _, err := os.Stat(h["gcode_path"].(string)); err != nil {
		t.Errorf("gcode_path does not exist: %v", err)
	}
	if h["upload_name"] != "Cube_plate1.gcode" {
		t.Errorf("upload_name = %v", h["upload_name"])
	}

	// The project shows the slice.
	if got := pf.ok(t, "get_project", map[string]any{"project": id}); !strings.Contains(got, "Last slice") {
		t.Errorf("get_project after slice:\n%s", got)
	}

	summary := pf.ok(t, "get_slice_report", map[string]any{"project": id})
	contains(t, "summary", summary, "Plate 1", "Creality_Print")
	fil := pf.ok(t, "get_slice_report", map[string]any{"project": id, "section": "filaments"})
	contains(t, "filaments", fil, "T0", "T1", "1.50")
	objs := pf.ok(t, "get_slice_report", map[string]any{"project": id, "section": "objects"})
	contains(t, "objects", objs, "cube_id_0_copy_0")
	layers := pf.ok(t, "get_slice_report", map[string]any{"project": id, "section": "layers"})
	contains(t, "layers", layers, "2 layer(s)")
	settings := pf.ok(t, "get_slice_report", map[string]any{"project": id, "section": "settings"})
	contains(t, "settings", settings, "differ from", "wall_loops: 3 -> 4")

	lr := call(t, pf.cs, "get_slice_report", map[string]any{"project": id, "section": "layer", "layer": 2})
	if lr.IsError || len(images(lr)) != 1 {
		t.Fatalf("layer report: error %v, %d image(s):\n%s", lr.IsError, len(images(lr)), text(t, lr))
	}
	contains(t, "layer", text(t, lr), "Layer 2", "Outer wall")
	none := call(t, pf.cs, "get_slice_report", map[string]any{"project": id, "section": "layer", "z": 0.2, "preview": "none"})
	if none.IsError || len(images(none)) != 0 {
		t.Errorf("layer by z without a picture: error %v, %d image(s)", none.IsError, len(images(none)))
	}
	if e := pf.errText(t, "get_slice_report", map[string]any{"project": id, "section": "layer"}); !strings.Contains(e, "invalid_input") {
		t.Errorf("layer without layer or z: %s", e)
	}
	if e := pf.errText(t, "get_slice_report", map[string]any{"project": id, "section": "layer", "layer": 99}); !strings.Contains(e, "invalid_input") {
		t.Errorf("layer 99: %s", e)
	}
}

func TestSliceReportBeforeAnySliceAndAfterAChange(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.withModel(t, "Cube")
	if e := pf.errText(t, "get_slice_report", map[string]any{"project": id}); !strings.Contains(e, "slice_project") {
		t.Errorf("report before a slice: %s", e)
	}
	pf.ok(t, "slice_project", map[string]any{"project": id, "background": false})
	pf.ok(t, "update_settings", map[string]any{"project": id, "values": map[string]any{"wall_loops": 5}})
	rep := pf.ok(t, "get_slice_report", map[string]any{"project": id})
	contains(t, "stale report", rep, "changed after this slice")
	if frontOf(t, rep)["stale"] != true {
		t.Errorf("front = %v", frontOf(t, rep))
	}
}

func TestSliceWithoutObjectsFails(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.create(t, "Empty")
	if e := pf.errText(t, "slice_project", map[string]any{"project": id}); !strings.Contains(e, "add_model") {
		t.Errorf("slice of an empty project: %s", e)
	}
}

func TestSliceInTheBackgroundAndStatus(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.withModel(t, "Cube")
	pf.exec.block = make(chan struct{})

	out := pf.ok(t, "slice_project", map[string]any{"project": id, "background": true})
	front := frontOf(t, out)
	job, _ := front["job_id"].(string)
	if front["state"] != "running" || job == "" {
		t.Fatalf("front = %v", front)
	}
	contains(t, "background reply", out, "get_slice_status")

	running := pf.ok(t, "get_slice_status", map[string]any{"job_id": job})
	if frontOf(t, running)["state"] != "running" {
		t.Errorf("status = %s", running)
	}
	list := pf.ok(t, "get_slice_status", nil)
	contains(t, "job list", list, job)

	close(pf.exec.block)
	var done string
	deadline := time.Now().Add(30 * time.Second)
	for time.Now().Before(deadline) {
		done = pf.ok(t, "get_slice_status", map[string]any{"job_id": job})
		if frontOf(t, done)["state"] == "finished" {
			break
		}
		time.Sleep(20 * time.Millisecond)
	}
	if frontOf(t, done)["state"] != "finished" {
		t.Fatalf("the job did not finish:\n%s", done)
	}
	contains(t, "finished status", done, "gcode_path", "start_print")
	if e := pf.errText(t, "get_slice_status", map[string]any{"job_id": "slice-nope"}); !strings.Contains(e, "not_found") {
		t.Errorf("unknown job: %s", e)
	}
	if e := pf.errText(t, "get_slice_status", map[string]any{"cancel": true}); !strings.Contains(e, "job_id") {
		t.Errorf("cancel without a job: %s", e)
	}
}

func TestCancelAJob(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.withModel(t, "Cube")
	pf.exec.block = make(chan struct{})
	pf.exec.killed = make(chan struct{})
	pf.exec.started = make(chan struct{})
	job := frontOf(t, pf.ok(t, "slice_project", map[string]any{"project": id, "background": true}))["job_id"].(string)
	select {
	case <-pf.exec.started:
	case <-time.After(30 * time.Second):
		t.Fatal("the slicer run did not start")
	}
	got := pf.ok(t, "get_slice_status", map[string]any{"job_id": job, "cancel": true})
	if frontOf(t, got)["state"] != "cancelled" {
		t.Errorf("cancel = %s", got)
	}
	select {
	case <-pf.exec.killed:
	case <-time.After(30 * time.Second):
		t.Error("the slicer run was not stopped")
	}
}

func TestServerStopsItsJobsOnShutdown(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.withModel(t, "Cube")
	pf.exec.block = make(chan struct{})
	pf.exec.killed = make(chan struct{})
	pf.exec.started = make(chan struct{})
	pf.ok(t, "slice_project", map[string]any{"project": id, "background": true})
	select {
	case <-pf.exec.started:
	case <-time.After(30 * time.Second):
		t.Fatal("the slicer run did not start")
	}
	pf.srv.env.stopJobs()
	select {
	case <-pf.exec.killed:
	case <-time.After(30 * time.Second):
		t.Error("a running slice survived the shutdown")
	}
}

func TestProjectToolsWithoutAnInstall(t *testing.T) {
	f := newFixture(t, func(fi *fakeInstall, _ *Deps) { fi.install = slicer.Install{Reason: "not installed"} })
	e := f.errText(t, "list_projects", nil)
	contains(t, "no install", e, "unavailable")
}

func TestSliceFileImportsSlicesAndCopiesTheGCode(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.withModel(t, "Cube")
	file := filepath.Join(t.TempDir(), "cube.3mf")
	pf.ok(t, "export_project", map[string]any{"project": id, "path": file})
	before, err := os.ReadFile(file)
	if err != nil {
		t.Fatal(err)
	}

	out := filepath.Join(t.TempDir(), "gcode")
	res := pf.srv.SliceFile(context.Background(), SliceFileArgs{Path: file, Out: out})
	body := text(t, res)
	if res.IsError {
		t.Fatalf("SliceFile failed:\n%s", body)
	}
	dest := filepath.Join(out, "cube_plate1.gcode")
	contains(t, "slice file", body, dest, "get_filaments")
	if _, err := os.Stat(dest); err != nil {
		t.Errorf("the G-code was not copied: %v", err)
	}
	after, _ := os.ReadFile(file)
	if string(before) != string(after) {
		t.Error("the source file was changed")
	}
	// Only the exported project is left: the temporary one was deleted.
	items, err := pf.store.List()
	if err != nil || len(items) != 1 {
		t.Errorf("projects after --out = %v, %v", items, err)
	}

	// Without --out the project stays and the path points into the store.
	res = pf.srv.SliceFile(context.Background(), SliceFileArgs{Path: file, Plate: 1})
	if res.IsError || !strings.Contains(text(t, res), "cube_plate1.gcode") {
		t.Fatalf("SliceFile without out:\n%s", text(t, res))
	}
	if items, _ := pf.store.List(); len(items) != 2 {
		t.Errorf("projects = %d, want 2", len(items))
	}
	if bad := pf.srv.SliceFile(context.Background(), SliceFileArgs{Path: filepath.Join(t.TempDir(), "none.3mf")}); !bad.IsError {
		t.Error("a missing file was accepted")
	}
}

func TestRecentProjectsReport(t *testing.T) {
	pf := newProjFixture(t)
	if got := text(t, pf.srv.RecentProjects(context.Background())); !strings.Contains(got, "No projects yet") {
		t.Errorf("empty: %s", got)
	}
	id := pf.create(t, "Bracket")
	if got := text(t, pf.srv.RecentProjects(context.Background())); !strings.Contains(got, id) {
		t.Errorf("one project: %s", got)
	}
}

// slice_project waits up to `wait` seconds in the foreground and hands over the
// job id when the slice takes longer.
func TestSliceProjectWaitsThenHandsOverTheJob(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.withModel(t, "Cube")
	out := pf.ok(t, "slice_project", map[string]any{"project": id})
	front := frontOf(t, out)
	if front["state"] != "finished" {
		t.Fatalf("a fast slice did not return its result:\n%s", out)
	}
	if plates, _ := front["plates"].([]any); len(plates) != 1 || plates[0].(map[string]any)["changes"] == nil {
		t.Errorf("plates lack the filament changes: %v", front["plates"])
	}
	// A slow slice: the wait (1 s) ends first and the reply says how to poll.
	pf.exec.block = make(chan struct{})
	out = pf.ok(t, "slice_project", map[string]any{"project": id, "wait": 1, "thumbnails": false})
	front = frontOf(t, out)
	if front["state"] != "running" || front["job_id"] == nil {
		t.Fatalf("a slow slice did not return the job:\n%s", out)
	}
	if !strings.Contains(out, "still running after 1 s") || !strings.Contains(out, "get_slice_status") {
		t.Errorf("no polling advice:\n%s", out)
	}
	pf.finishJob(t, front["job_id"].(string))
	// background true returns at once, whatever the wait.
	pf.exec.block = make(chan struct{})
	start := time.Now()
	out = pf.ok(t, "slice_project", map[string]any{"project": id, "background": true, "wait": 600})
	if frontOf(t, out)["state"] != "running" || time.Since(start) > 20*time.Second {
		t.Errorf("background did not return at once:\n%s", out)
	}
	close(pf.exec.block)
	pf.exec.block = nil
	for name, args := range map[string]map[string]any{
		"timeout above 1800": {"timeout": 5000}, "wait above 600": {"wait": 601}, "wait below 1": {"wait": 0},
	} {
		args["project"] = id
		if res := call(t, pf.cs, "slice_project", args); !res.IsError {
			t.Errorf("%s was accepted", name)
		}
	}
}

// finishJob releases a blocked fake slicer and waits until the job is finished.
func (pf *projFixture) finishJob(t *testing.T, job string) {
	t.Helper()
	close(pf.exec.block)
	pf.exec.block = nil
	deadline := time.Now().Add(30 * time.Second)
	for time.Now().Before(deadline) {
		if frontOf(t, pf.ok(t, "get_slice_status", map[string]any{"job_id": job}))["state"] == "finished" {
			return
		}
		time.Sleep(20 * time.Millisecond)
	}
	t.Fatalf("job %s did not finish", job)
}

func TestAddModelObjectsAndModifierRotationAreWired(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.withModel(t, "Wired")
	obj := strings.TrimSuffix(filepath.Base(pf.stl), filepath.Ext(pf.stl))
	// objects names objects of a 3MF; an STL has none.
	e := pf.errText(t, "add_model", map[string]any{"project": id, "path": pf.stl, "objects": []string{"x"}})
	contains(t, "objects on an STL", e, "single model")
	pf.ok(t, "add_modifier", map[string]any{"project": id, "object": obj, "kind": "negative_part", "shape": "box", "size": []float64{20, 4, 4}, "rotation": []float64{0, 0, 45}})
	if res := call(t, pf.cs, "add_modifier", map[string]any{"project": id, "object": obj, "kind": "negative_part", "shape": "box", "size": []float64{20, 4, 4}, "rotation": []float64{45}}); !res.IsError {
		t.Error("a rotation with one angle was accepted")
	}
}

// v0.1.2: replies say what the tools added or moved.
func TestRepliesNoteAddedLayerHeightAndMovedObjects(t *testing.T) {
	pf := newProjFixture(t)
	id := pf.create(t, "Notes")
	x1, x2 := 100.0, 105.0
	for i, x := range []float64{x1, x2} {
		pf.ok(t, "add_model", map[string]any{"project": id, "path": pf.stl, "name": "part" + strconv.Itoa(i), "position": []float64{x, 100}, "include_screenshot": false})
	}
	out := pf.ok(t, "set_height_ranges", map[string]any{"project": id, "object": "part0", "ranges": []map[string]any{
		{"from_z": 2, "to_z": 6, "values": map[string]any{"wall_loops": 5}}}, "include_screenshot": false})
	contains(t, "range note", bodyOf(out), "layer_height", "added", "crashes")
	// update_settings that changes nothing keeps the revision.
	before := frontOf(t, pf.ok(t, "get_project", map[string]any{"project": id}))["revision"]
	same := pf.ok(t, "update_settings", map[string]any{"project": id, "values": map[string]any{"wall_loops": 3}})
	if got := frontOf(t, same)["revision"]; got != before {
		t.Errorf("revision %v -> %v for a call that changes nothing", before, got)
	}
	slice := pf.ok(t, "slice_project", map[string]any{"project": id, "arrange": true})
	contains(t, "moved", bodyOf(slice), "Objects moved by arrange or orient", "part")
}
